require 'spec_helper'

SimpleCov.command_name('Step') unless RUBY_VERSION.to_s < '1.9.0'

describe 'Step, Unit' do

  let(:clazz) { CukeModeler::Step }
  let(:step) { clazz.new }


  describe 'common behavior' do

    it_should_behave_like 'a modeled element'
    it_should_behave_like 'a sourced element'
    it_should_behave_like 'a raw element'

  end


  describe 'unique behavior' do

    it 'has a base' do
      step.should respond_to(:base)
    end

    it 'can change its base' do
      expect(step).to respond_to(:base=)

      step.base = :some_base
      step.base.should == :some_base
      step.base = :some_other_base
      step.base.should == :some_other_base
    end

    it 'starts with no base' do
      step.base.should == nil
    end

    it 'has a block' do
      step.should respond_to(:block)
    end

    it 'can change its block' do
      expect(step).to respond_to(:block=)

      step.block = :some_block
      step.block.should == :some_block
      step.block = :some_other_block
      step.block.should == :some_other_block
    end

    it 'starts with no block' do
      step.block.should == nil
    end

    it 'has a keyword' do
      step.should respond_to(:keyword)
    end

    it 'can change its keyword' do
      expect(step).to respond_to(:keyword=)

      step.keyword = :some_keyword
      step.keyword.should == :some_keyword
      step.keyword = :some_other_keyword
      step.keyword.should == :some_other_keyword
    end

    it 'starts with no keyword' do
      step.keyword.should == nil
    end

    it 'can be parsed from stand alone text' do
      source = '* test step'

      expect { @element = clazz.new(source) }.to_not raise_error

      # Sanity check in case instantiation failed in a non-explosive manner
      @element.base.should == 'test step'
    end

    it 'provides a descriptive filename when being parsed from stand alone text' do
      source = "bad step text\n And a step\n @foo"

      expect { clazz.new(source) }.to raise_error(/'cuke_modeler_stand_alone_step\.feature'/)
    end

    it 'stores the original data generated by the parsing adapter', :gherkin4 => true do
      step = clazz.new("* test step")
      raw_data = step.raw_element

      expect(raw_data.keys).to match_array([:type, :location, :keyword, :text])
      expect(raw_data[:type]).to eq(:Step)
    end

    it 'stores the original data generated by the parsing adapter', :gherkin3 => true do
      step = clazz.new("* test step")
      raw_data = step.raw_element

      expect(raw_data.keys).to match_array([:type, :location, :keyword, :text])
      expect(raw_data[:type]).to eq(:Step)
    end

    it 'stores the original data generated by the parsing adapter', :gherkin2 => true do
      step = clazz.new("* test step")
      raw_data = step.raw_element

      expect(raw_data.keys).to match_array(['keyword', 'name', 'line'])
      expect(raw_data['keyword']).to eq('* ')
    end

    it 'contains some kind of block' do
      block = :block
      everything = [block]

      step.block = block

      expect(step.children).to match_array(everything)
    end


    describe 'step output edge cases' do

      it 'is a String' do
        step.to_s.should be_a(String)
      end


      context 'a new step object' do

        let(:step) { clazz.new }


        it 'can output an empty step' do
          expect { step.to_s }.to_not raise_error
        end

        it 'can output a step that has only a keyword' do
          step.keyword = '*'

          expect { step.to_s }.to_not raise_error
        end

        it 'can output a step that has only a base' do
          step.base = 'step base'

          expect { step.to_s }.to_not raise_error
        end

      end

    end

    it 'can gracefully be compared to other types of objects' do
      # Some common types of object
      [1, 'foo', :bar, [], {}].each do |thing|
        expect { step == thing }.to_not raise_error
        expect(step == thing).to be false
      end
    end

  end

end
