ENV['MOST_CURRENT_GHERKIN_VERSION'] ||= '42'
ENV['GHERKIN_MAJOR_VERSIONS_WITHOUT_CUCUMBER_SUPPORT'] ||= '9,11,12,16,17,19,21,28,29,40,41,42'

ENV['CUKE_MODELER_REPORT_FOLDER'] ||= "#{__dir__}/reports"
ENV['CUKE_MODELER_RSPEC_REPORT_NAME'] ||= 'rspec_report'
ENV['CUKE_MODELER_RSPEC_REPORT_HTML_FILE'] ||= "#{ENV.fetch('CUKE_MODELER_RSPEC_REPORT_NAME')}.html"
ENV['CUKE_MODELER_CUCUMBER_REPORT_NAME'] ||= 'cucumber_report'
ENV['CUKE_MODELER_CUCUMBER_REPORT_HTML_FILE'] ||= "#{ENV.fetch('CUKE_MODELER_CUCUMBER_REPORT_NAME')}.html"
