module CukeModeler

  # A mix-in module containing methods used by models that are parsed from source text.

  module Parsed

    # The parsing data for this element that was generated by the parsing engine (i.e. the *gherkin* gem)
    attr_accessor :parsing_data

  end
end
